"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar ASN.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar Baseline.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar AvailabilityRespond.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar AvailabilitySend.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar BillOfLading.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar CountryCode.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar CurrencyCode.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar ElementCode.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar Invoice.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar MTR.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar OrderStatusSend.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar Payment.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar POConfirm.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar POIssue.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar POReceipt.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar RFQRespond.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar RFQRevision.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar RFQSend.xsd
"C:\Program Files (x86)\Java\jdk1.8.0_112\jre\bin"\java.exe -jar xsdvi\dist\lib\xsdvi.jar SustainabilityRespond.xsd